server:
  port: 8080
  
spring:
  application:
    name: api-management

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/entreprise_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.server: DEBUG