spring:
  application:
    name: api-management

  datasource:
    url: jdbc:postgresql://localhost:5432/entreprise_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

jwt:
  jwtSecret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
  jwtExpirationMs: 86400000